spring:
  main:
    allow-bean-definition-overriding: true
  server:
    port: 8081
    shutdown: graceful
  datasource:
    url: jdbc:mysql://localhost:3306/monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 520886Jy@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      keepalive-time: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
    chunk:
      size: 1000
  lifecycle:
    timeout-per-shutdown-phase: 30s
mybatis:
  configuration:
    map-underscore-to-camel-case: true
ai:
  service:
    url: http://127.0.0.1:5000/ai/detect
jwt:
  secret: YangMieMie2026MonitorSecretKeyVeryLong1234567890abcdef
  expire: 86400000 # 24小时过期，单位毫秒